version: "3.9"
networks:
  web: {}

name: webpage
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"        # external access: http://<pi-ip>:8000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RUST_LOG: info
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 10

