services:
  django:
    build:
      context: .
      dockerfile: django/docker/Dockerfile
    container_name: django
    command: >
          bash -c "python manage.py migrate &&
                   python manage.py collectstatic --noinput &&
                   chown -R www-data:www-data /django/staticfiles &&
                   chmod -R 755 /django/staticfiles &&  
                   daphne -b 0.0.0.0 -p 8000 personalWebpage.asgi:application"
    volumes:
      - ./django:/django
      - ./utils:/utils
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_HOST=redis
      - PYTHONPATH=/utils
    networks:
      - webpage_network
      - kafka_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./django/staticfiles:/django/staticfiles
      - ./django/media:/django/media
      - ./django/docker/nginx_development.conf:/etc/nginx/nginx.conf # Comment for production
      #- ./django/docker/nginx_production.conf:/etc/nginx/nginx.conf # Uncomment for production
      #- /etc/letsencrypt/:/etc/letsencrypt # Uncomment for production
      
    ports:
      - "80:80"
      - "443:443"  # Expose port 443 for HTTPS
    depends_on:
      - django
    networks:
      - webpage_network

networks:
  kafka_network:
    driver: bridge
  webpage_network:
    name: webpage_network
    driver: bridge

volumes:
  postgres_data:
