services:
  django:
    build:
      context: .
      dockerfile: django/hosting/Dockerfile
    container_name: django
    volumes:
      - ./django:/django
      - ./utils:/utils
    command: /django/hosting/django_bash_command.sh
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_HOST=redis
      - PYTHONPATH=/utils
    networks:
      - webpage_network
      - kafka_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./django/staticfiles:/django/staticfiles
      - ./django/media:/django/media
      
    ports:
      - "80:80"
      - "443:443"  # Expose port 443 for HTTPS
    depends_on:
      - django
    networks:
      - webpage_network

networks:
  kafka_network:
    driver: bridge
  webpage_network:
    name: webpage_network
    driver: bridge

volumes:
  postgres_data:
