services:
  django:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    container_name: django_app
    command: >
          bash -c "python manage.py migrate &&
                   python manage.py collectstatic --noinput &&
                   chown -R www-data:www-data /personalWebpage/django/staticfiles &&
                   chmod -R 755 /personalWebpage/django/staticfiles &&
                   daphne -b 0.0.0.0 -p 8000 personalWebpage.asgi:application"
    volumes:
      - ./django:/personalWebpage/django
      - ./utils:/personalWebpage/django/utils
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://Krusovice:fedefrede@postgres_db:5432/personalWebpage_db
      - REDIS_HOST=redis
    networks:
      - shared_network

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx_dev.conf:/etc/nginx/nginx.conf # Comment for production
      #- ./nginx.conf:/etc/nginx/nginx.conf # Uncomment for production
      - ./django/staticfiles:/personalWebpage/django/staticfiles
      - ./django/media:/personalWebpage/django/media
      #- /etc/letsencrypt/:/etc/letsencrypt # Uncomment for production
    ports:
      - "80:80"
      - "443:443"  # Expose port 443 for HTTPS
    depends_on:
      - django
    networks:
      - shared_network

networks:
  kafka_network:
    driver: bridge
  shared_network:
    driver: bridge

volumes:
  postgres_data:
