# Generated by Django 5.1.3 on 2025-05-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_column='ticker', max_length=10)),
                ('date', models.DateField(db_column='date')),
                ('closing_price', models.DecimalField(db_column='closing_price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'stockmarket.stock_prices',
                'managed': False,
            },
        ),
    ]
