# Generated by Django 5.1.3 on 2025-05-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockprice',
            table='stock_prices',
        ),
    ]
