CREATE TABLE literature.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    keywords TEXT NOT NULL,
    timestamp_upload TIMESTAMPTZ DEFAULT NOW(),
    timestamp_modified TIMESTAMPTZ DEFAULT NOW(),
    views BIGINT NOT NULL DEFAULT 0,
    UNIQUE (title, author)
);
