CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email CITEXT NOT NULL UNIQUE,
    username CITEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,

    first_name TEXT NOT NULL CHECK (length(first_name) <= 100),
    last_name  TEXT NOT NULL CHECK (length(last_name)  <= 100),
    company    TEXT NULL CHECK (length(company) <= 200),

    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user','admin')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login TIMESTAMPTZ
);

-- (Valgfrit) Basalt format-tjek af email (ikke perfekt, men filtrerer de værste):
CREATE OR REPLACE FUNCTION is_valid_email(text) RETURNS boolean AS $$
    SELECT $1 ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$';
$$ LANGUAGE sql IMMUTABLE;

ALTER TABLE users
  ADD CONSTRAINT email_format_ok CHECK (is_valid_email(email));
