name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cleanup before deployment
        run: |
          git reset --hard HEAD
          git clean -fd

      - name: Setting permissions
        run: |
          chmod +x start_prod.sh
          chmod +x django/hosting/django_bash_command.sh

          echo "" >> .env
          echo "AIRFLOW_UID=$(id -u)" >> .env

      - name: Run deployment script
        run: |

          ./start_prod.sh

      - name: Permissions after deployment
        run: |
          sudo chown -R $USER:$USER /home/user/actions-runner/_work