name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cleanup before deployment
        run: |
          git reset --hard HEAD
          git clean -fd

      - name: Prepare Nginx and django permissions
        run: |
          chmod -R 755 ../../../../secrets-and-database/media
          chmod -R 755 ./django/staticfiles
          chmod +x django/hosting/django_bash_command.sh


      - name: Preparing Airflow
        run: |
          echo "" >> .env
          echo "AIRFLOW_UID=$(id -u)" >> .env

      - name: Run deployment script
        run: |
          chmod +x start_prod.sh
          ./start_prod.sh

      - name: Permissions after deployment
        run: |
          sudo chown -R $USER:$USER /home/user/actions-runner/_work

